version: "3"
services:
  vivado:
    build: .
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER}
    privileged: true
    network_mode: "host"
    # user: '$(id -u):$(id -g)'
    # user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}
      - ${PROJECTDIR}:/project
    args:
      - VIVADO_VERSION=${VIVADO_VERSION}
      - VIVADO_SETUP=${VIVADO_SETUP}
      - DOCKERHOST_IP=${DOCKERHOST_IP}
