version: "3"
services:
  vivado:
    build:
      context: .
      args:
        - VIVADO_VERSION=${VIVADO_VERSION}
        - VIVADO_SETUP=${VIVADO_SETUP}
        - DOCKERHOST_IP=${DOCKERHOST_IP}
    image: "futafi/vivado:${VIVADO_VERSION}"
    container_name: vivado
    privileged: true
    network_mode: "host"
    # user: '$(id -u):$(id -g)'
    # user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}
      - ${PROJECTDIR}:/project
